/**
 * Mock data para receitas
 * Será substituído pela API real quando disponível
 */

export const mockRecipesCarousel = [
  {
    id: '1',
    nome: 'Macarrão à Carbonara',
    descricao: 'Clássico italiano com bacon e ovos',
    tempoPreparo: 20,
    tempoCozimento: 15,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    avaliacoes: 4.8,
    numeroAvaliacoes: 256,
    calorias: 520,
  },
  {
    id: '2',
    nome: 'Frango Xadrez',
    descricao: 'Receita oriental com vegetais crocantes',
    tempoPreparo: 25,
    tempoCozimento: 20,
    dificuldade: 'Médio',
    imagem: 'https://images.unsplash.com/photo-1633203777956-8f6530120795?w=400&h=300&fit=crop',
    avaliacoes: 4.6,
    numeroAvaliacoes: 189,
    calorias: 380,
  },
  {
    id: '3',
    nome: 'Risoto de Cogumelo',
    descricao: 'Cremoso e sofisticado para jantares',
    tempoPreparo: 30,
    tempoCozimento: 25,
    dificuldade: 'Médio',
    imagem: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop',
    avaliacoes: 4.7,
    numeroAvaliacoes: 142,
    calorias: 450,
  },
  {
    id: '4',
    nome: 'Salada Caesar',
    descricao: 'Fresca e levinha com croutons caseiros',
    tempoPreparo: 15,
    tempoCozimento: 0,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    avaliacoes: 4.5,
    numeroAvaliacoes: 203,
    calorias: 280,
  },
  {
    id: '5',
    nome: 'Brownie de Chocolate',
    descricao: 'Sobremesa fácil e irresistível',
    tempoPreparo: 20,
    tempoCozimento: 30,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop',
    avaliacoes: 4.9,
    numeroAvaliacoes: 412,
    calorias: 350,
  },
];

export const mockAllRecipes = [
  ...mockRecipesCarousel,
  {
    id: '6',
    nome: 'Bife à Parmegiana',
    descricao: 'Clássico molho de tomate com queijo derretido',
    tempoPreparo: 15,
    tempoCozimento: 35,
    dificuldade: 'Médio',
    imagem: 'https://images.unsplash.com/photo-1598694662202-4e5915edf426?w=400&h=300&fit=crop',
    avaliacoes: 4.4,
    numeroAvaliacoes: 178,
    calorias: 680,
  },
  {
    id: '7',
    nome: 'Salmão Grelhado',
    descricao: 'Peixe fresco com limão e ervas',
    tempoPreparo: 10,
    tempoCozimento: 15,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1606787620708-3bab9f16d946?w=400&h=300&fit=crop',
    avaliacoes: 4.7,
    numeroAvaliacoes: 267,
    calorias: 320,
  },
  {
    id: '8',
    nome: 'Brigadeiro Gourmet',
    descricao: 'Doce clássico com toque especial',
    tempoPreparo: 10,
    tempoCozimento: 15,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop',
    avaliacoes: 4.6,
    numeroAvaliacoes: 534,
    calorias: 200,
  },
];

export const mockRecipeDetails = {
  '1': {
    id: '1',
    nome: 'Macarrão à Carbonara',
    descricao: 'Clássico italiano com bacon e ovos',
    tempoPreparo: 20,
    tempoCozimento: 15,
    dificuldade: 'Fácil',
    imagem: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop',
    avaliacoes: 4.8,
    numeroAvaliacoes: 256,
    calorias: 520,
    rendimento: '4 porções',
    ingredientes: [
      { id: '1', nome: 'Macarrão', quantidade: 400, unidade: 'g' },
      { id: '2', nome: 'Bacon', quantidade: 200, unidade: 'g' },
      { id: '3', nome: 'Ovos', quantidade: 3, unidade: 'un' },
      { id: '4', nome: 'Queijo Parmesão', quantidade: 100, unidade: 'g' },
      { id: '5', nome: 'Sal e Pimenta', quantidade: 1, unidade: 'gosto' },
    ],
    modo: [
      'Cozinhe o macarrão em água salgada até ficar al dente',
      'Corte o bacon em cubos e frite até ficar crocante',
      'Bata os ovos com o queijo ralado',
      'Escorra o macarrão e misture com o bacon ainda quente',
      'Desligue do fogo e adicione a mistura de ovos, mexendo rapidamente',
      'Tempere com sal e pimenta a gosto',
      'Sirva imediatamente com mais queijo por cima',
    ],
    dicas: [
      'Use ovos em temperatura ambiente para evitar que cozinhem demais',
      'O bacon deve estar morno para temperar o prato',
      'Não use creme de leite na receita tradicional',
    ],
  },
  '2': {
    id: '2',
    nome: 'Frango Xadrez',
    descricao: 'Receita oriental com vegetais crocantes',
    tempoPreparo: 25,
    tempoCozimento: 20,
    dificuldade: 'Médio',
    imagem: 'https://images.unsplash.com/photo-1633203777956-8f6530120795?w=600&h=400&fit=crop',
    avaliacoes: 4.6,
    numeroAvaliacoes: 189,
    calorias: 380,
    rendimento: '4 porções',
    ingredientes: [
      { id: '1', nome: 'Peito de Frango', quantidade: 600, unidade: 'g' },
      { id: '2', nome: 'Pimentão Vermelho', quantidade: 1, unidade: 'un' },
      { id: '3', nome: 'Pimentão Amarelo', quantidade: 1, unidade: 'un' },
      { id: '4', nome: 'Cenoura', quantidade: 1, unidade: 'un' },
      { id: '5', nome: 'Alho', quantidade: 3, unidade: 'dente' },
      { id: '6', nome: 'Gengibre', quantidade: 1, unidade: 'colher' },
      { id: '7', nome: 'Molho de Soja', quantidade: 3, unidade: 'colher' },
      { id: '8', nome: 'Vinagre de Arroz', quantidade: 1, unidade: 'colher' },
    ],
    modo: [
      'Corte o frango em cubos médios',
      'Pique os vegetais em cubos também',
      'Aqueça óleo em uma frigideira ou wok',
      'Refogue o alho e o gengibre',
      'Adicione o frango e cozinhe até ficar branco',
      'Adicione os vegetais em ordem de dureza',
      'Tempere com molho de soja e vinagre',
      'Sirva quente com arroz branco',
    ],
    dicas: [
      'O segredo é cortar tudo em tamanho uniforme',
      'Prepare todos os ingredientes antes de começar',
      'Use fogo alto para os vegetais ficarem crocantes',
    ],
  },
};

export const mockProductCategories = [
  {
    id: '1',
    nome: 'Frutas e Vegetais',
    icone: '🥬',
    cor: '#4CAF50',
  },
  {
    id: '2',
    nome: 'Carnes e Peixes',
    icone: '🥩',
    cor: '#FF6B6B',
  },
  {
    id: '3',
    nome: 'Laticínios',
    icone: '🥛',
    cor: '#FFD93D',
  },
  {
    id: '4',
    nome: 'Grãos e Cereais',
    icone: '🌾',
    cor: '#6BCB77',
  },
];
